version: '3.7'

# Define services
services:
  db:
    image: postgres:11.5-alpine
    restart: always
    tty: true
    environment:
      POSTGRES_USER: fp
      POSTGRES_PASSWORD: local
      POSTGRES_DB: payment_gateway
    volumes:
      - "pg_data_vol:/var/lib/postgresql/data"
      - ./build/database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      - net_db

  standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    ports:
      - "8092:8080"
      - "6650:6650"
    networks:
      - net_pulsar

  discovery:
    build:
      context: .
      dockerfile: discovery-server/deployment/docker/Dockerfile
    restart: always
    tty: true
    command: >
      java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar
    expose:
      - 8787
    ports:
      - "8787:8787"
    networks:
      - net_discovery

  sms-provider:
    build:
      context: .
      dockerfile: sms-provider/deployment/docker/Dockerfile
    restart: always
    tty: true
    depends_on:
      - discovery
    command: >
      java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar
    expose:
      - 12103
    ports:
      - "12103:12103"
    networks:
      - net_discovery

  payment-provider1:
    build:
      context: .
      dockerfile: payment-provider1/deployment/docker/Dockerfile
    restart: always
    tty: true
    depends_on:
      - discovery
    command: >
      java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar
    expose:
      - 12101
    ports:
      - "12101:12101"
    networks:
      - net_discovery

  payment-provider2:
    build:
      context: .
      dockerfile: payment-provider2/deployment/docker/Dockerfile
    restart: always
    tty: true
    depends_on:
      - discovery
    command: >
      java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar
    expose:
      - 12102
    ports:
      - "12102:12102"
    networks:
      - net_discovery

  payment-gateway:
    build:
      context: .
      dockerfile: payment-provider2/deployment/docker/Dockerfile
    restart: always
    tty: true
    depends_on:
      - discovery
      - db
      - standalone
    command: >
      java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar
    expose:
      - 12100
    ports:
      - "12100:12100"
    networks:
      - net_discovery
      - net_db
      - net_pulsar

networks:
  net_db:
  net_pulsar:
  net_discovery:

volumes:
  pg_data_vol:
